---
sidebar: sidebar 
permalink: scpivs44_log_in_to_the_snapcenter_vmware_vsphere_web_client.html 
keywords:  
summary: Quando o plug-in do SnapCenter para VMware vSphere é implantado, ele instala um cliente da Web do VMware vSphere no vCenter, que é exibido na tela do vCenter com outros clientes da Web do vSphere. 
---
= Faça login no Cliente Web do VMware vSphere do SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando o plug-in do SnapCenter para VMware vSphere é implantado, ele instala um cliente da Web do VMware vSphere no vCenter, que é exibido na tela do vCenter com outros clientes da Web do vSphere.

.Antes de começar
O TLS (Transport Layer Security) deve estar habilitado no vCenter. Consulte a documentação da VMware.

.Passos
. No seu navegador, navegue até o VMware vSphere vCenter.
. Na tela VMware, *clique em vSphere Client (HTML5)*.
. Inicie sessão na página *Início de sessão único do VMware vCenter*.
+

IMPORTANT: Clique no botão *Login*. Devido a um problema conhecido da VMware, não use a CHAVE ENTER para fazer login. Para obter detalhes, consulte a documentação da VMware sobre problemas do cliente de host incorporado ESXi.

. Na página *Cliente Web do VMware vSphere*, clique em Menu na barra de ferramentas e selecione *Plug-in do SnapCenter para VMware vSphere*.

